In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([1,3,3,3])

In [4]:
arr

array([1, 3, 3, 3])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3,3),5) # 3X3 and value == 5 

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.arange(1,100,9)  # it give value from first to 2nd with add of 1st and 2nd

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [13]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [17]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,13,14]])

In [18]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 13, 14]])

In [19]:
myarr.shape

(4, 3)

In [20]:
myarr.size

12

In [21]:
myarr.ndim

2

In [24]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,13,14]] , dtype='float32')

In [25]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 13., 14.]], dtype=float32)

In [27]:
n = myarr.astype('float64')

In [29]:
n.dtype

dtype('float64')

In [30]:
myarr.dtype

dtype('float32')

In [37]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,13,14]] , dtype='float32')

In [33]:
myarr.shape

(4, 3)

In [34]:
reshape = myarr.reshape((3,4))  # 3x4 = 12 then reshape successfull because phele bhi 4x3 = 12 tha

In [35]:
reshape

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 13., 14.]], dtype=float32)

In [38]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 13., 14.]], dtype=float32)