In [16]:
import numpy as np

myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,13,14]] , dtype='float32')

In [17]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 13., 14.]], dtype=float32)

In [18]:
flat = myarr.flatten()

In [19]:
flat

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 13., 14.],
      dtype=float32)

In [20]:
flat[0]

np.float32(1.0)

In [21]:
flat[3:6]

array([4., 5., 6.], dtype=float32)

In [22]:
flat[:5] # same as flat[0:5]

array([1., 2., 3., 4., 5.], dtype=float32)

In [24]:
flat[::2] # it take avery 2nd element

array([ 1.,  3.,  5.,  7.,  9., 13.], dtype=float32)

In [25]:
flat

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 13., 14.],
      dtype=float32)

In [26]:
b = flat[3:7]

In [27]:
b

array([4., 5., 6., 7.], dtype=float32)

In [28]:
b[0]= 44444

In [29]:
b

array([4.4444e+04, 5.0000e+00, 6.0000e+00, 7.0000e+00], dtype=float32)

In [30]:
flat

array([1.0000e+00, 2.0000e+00, 3.0000e+00, 4.4444e+04, 5.0000e+00,
       6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.1000e+01,
       1.3000e+01, 1.4000e+01], dtype=float32)

In [33]:
t = flat[3:7].copy()

In [34]:
t

array([4.4444e+04, 5.0000e+00, 6.0000e+00, 7.0000e+00], dtype=float32)

In [35]:
t[0]= 666666

In [36]:
t

array([6.66666e+05, 5.00000e+00, 6.00000e+00, 7.00000e+00], dtype=float32)

In [37]:
flat

array([1.0000e+00, 2.0000e+00, 3.0000e+00, 4.4444e+04, 5.0000e+00,
       6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.1000e+01,
       1.3000e+01, 1.4000e+01], dtype=float32)

In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])

In [43]:
arr[[4,3,5]]  # it will gives the indexes values

array([5, 4, 6])

In [46]:
mask = arr[arr>5]   # boolean masking

In [47]:
mask

array([6, 7, 8, 9])