In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
myarr.shape

(3, 3)

In [7]:
myarr.astype('int32')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [9]:
arr = np.array([1,2,3,4,5,6])

In [11]:
evenNum = arr[[1,3,5]]

In [13]:
evenNum

array([2, 4, 6])

In [14]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])

In [15]:
arr2.resize(3,3)

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
Arr = np.array([34,33,22,55,65,66,99,])

In [25]:
arr_greater_50 = Arr[Arr>50]

In [26]:
arr_greater_50

array([55, 65, 66, 99])

In [27]:
arr4 = arr[arr>2]

In [28]:
arr4

array([3, 4, 5, 6])