In [7]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr[0]

array([1, 2, 3])

In [10]:
np.sum(arr , axis=0) # axis= 0 matlab rows

array([12, 15, 18])

In [11]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [12]:
arr[0,1]  # multidimentional indexing

np.int64(2)

In [13]:
arr[0:2 , 1:3]

array([[2, 3],
       [5, 6]])

3D ARRAY



In [14]:
arr3D = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
                  
    [
        [7, 8, 9], 
       [10, 11, 12]
    ]
])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [20]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [22]:
# first row in 3D array 
print(arr3D[:,0,:])


[[1 2 3]
 [7 8 9]]


In [23]:
arr3D[:,0,:] = 0

In [24]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])