In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr.sum(axis=0)

array([12, 15, 18])

In [6]:
arr.sum(axis= 1)

array([ 6, 15, 24])

In [7]:
arr[0][2]

np.int64(3)

In [8]:
arr[1][0]

np.int64(4)

In [13]:
arr [2:3]

array([[7, 8, 9]])

In [15]:
arr[2:3,0:1]

array([[7]])

In [16]:
a4 = np.array([1,'ba',2])