In [55]:
import numpy as np

In [94]:
arr3 = np.array([[1,2,3,4,5,6,7,8,9]])

In [95]:
arr3

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [96]:
arr3.shape

(1, 9)

In [97]:
arr3.ndim

2

In [98]:
arr3.dtype

dtype('int64')

In [99]:
arr3.astype('int32')

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [100]:
arr = np.ones((2,4))

In [101]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
arr.reshape(4,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
arr3 = arr.flatten()

In [114]:
arr3

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
arr3.reshape(8,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [117]:
arr1 = np.ones((2,3))

In [118]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
arr1[1:2]

array([[1., 1., 1.]])

In [122]:
arr = arr1.flatten()

In [123]:
arr

array([1., 1., 1., 1., 1., 1.])

In [124]:
arr.ndim

1

In [127]:
arr[1:6]

array([1., 1., 1., 1., 1.])

In [128]:
arr = np.array([1.1,2.2,3.3])

In [130]:
arr.dtype

dtype('float64')

In [131]:
arr2 = arr.astype('int32')

In [132]:
arr2.dtype

dtype('int32')

In [133]:
arr2

array([1, 2, 3], dtype=int32)

In [136]:
mask =  arr2>2

In [140]:
arr8 = arr2[mask]

In [141]:
arr8

array([3], dtype=int32)

In [145]:
arr = np.array([1,2,3,4,5,6,7])

In [147]:
ind = 2,3,4,5

In [148]:
arr2

array([1, 2, 3], dtype=int32)

In [149]:
arr = np.random.randint(0,100,size=(3,3))

In [150]:
arr

array([[17, 68, 37],
       [42, 76, 28],
       [ 7, 72, 41]])

In [154]:
arr = np.random.randint(0,11)

In [155]:
arr

9

In [156]:
arr2 = np.arange(1,90,3)

In [157]:
arr2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88])