In [50]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [51]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2 = arr.flatten()

In [53]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr2[::2]

array([1, 3, 5, 7, 9])

In [55]:
arr3 = np.arange(1,10)

In [56]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
print(arr3[[0,5,2,3]])

[1 6 3 4]


In [58]:
mas = arr3>4

In [59]:
mas


array([False, False, False, False,  True,  True,  True,  True,  True])

In [60]:
result = arr3[mas]

In [61]:
result

array([5, 6, 7, 8, 9])

In [62]:
random = np.random.randint(0,11,size=(2,3))

In [63]:
random

array([[7, 5, 6],
       [1, 2, 0]])

In [64]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr3.resize(3,3)

In [66]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])