In [5]:
import numpy as np

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [9]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [10]:
arr[0][2]

np.int64(3)

In [11]:
arr[1,2]

np.int64(6)

In [12]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [19]:
arr = np.array([[[1,2,3],[4,5,6]],[[8,9,0],[3,4,5]]])

In [20]:
arr.shape

(2, 2, 3)

In [22]:
arr[:,:,0]

array([[1, 4],
       [8, 3]])

In [23]:
arr = np.zeros((2,3))

In [24]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr = np.eye(8)

In [26]:
arr

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
arr = np.arange(1,11)

In [28]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr = np.array([2,3,4])

In [40]:
arr

array([2, 3, 4])

In [44]:
arr2 = arr.astype('float32')

In [45]:
arr2.dtype

dtype('float32')

In [46]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

In [47]:
mean = data.mean(axis=0)

In [48]:
std = data.std(axis=0)

In [49]:
normalization_data = (data-mean)/std

In [50]:
normalization_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])