In [1]:
import numpy as np 

In [2]:
arr = np.ones((3,3))

In [3]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr2 = np.arange(1,11)

In [5]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr3 = np.random.randint(1,20,size=(3,3))

In [7]:
arr3

array([[13, 11,  9],
       [17, 14,  4],
       [17, 14,  8]])