In [2]:
import numpy as np
import time as time

In [5]:
size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [ x+y for x,y in zip(l1,l2)]
end = time.time()

print(end-start)

0.03547310829162598


In [6]:
size = 1_000_000
l1 = np.array(range(size))
l2 = np.array(range(size))

start = time.time()
add = l1+l2
end = time.time()

print(end-start)

0.012814044952392578


In [9]:
arr = np.array([[1,2,3],[4,5,6]])

In [11]:
type(arr)

numpy.ndarray

In [13]:
arr.shape

(2, 3)

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

In [17]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [23]:
arr = np.eye(4)

In [24]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
arr.size

16

In [28]:
arr.shape

(4, 4)

In [29]:
arr.ndim

2

In [30]:
arr.dtype

dtype('float64')

In [32]:
arr2 = np.array([1,2,3,4],dtype=np.float32)

In [33]:
arr2.dtype

dtype('float32')

In [34]:
arr3 = np.ones((2,3))

In [35]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
arr4 = arr3.reshape((3,2))

In [37]:
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
arr5 = arr3.flatten()

In [39]:
arr5

array([1., 1., 1., 1., 1., 1.])