In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
result = arr**2

In [8]:
result

array([ 1,  4,  9, 16, 25])

In [9]:
result+10

array([11, 14, 19, 26, 35])

In [14]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [21]:
arr3 = np.array([1,2,3])

In [22]:
ar = arr2 + arr3

In [23]:
ar

array([[2, 4, 6],
       [5, 7, 9]])

In [24]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

In [25]:
mean = data.mean()

In [26]:
std = data.std()

In [29]:
normalise_data = (data - mean)/std

In [31]:
normalise_data

array([[-1.8516402 , -0.9258201 ,  0.        ],
       [-1.38873015, -0.46291005,  0.46291005],
       [-0.9258201 ,  0.        ,  0.9258201 ],
       [-0.46291005,  0.46291005,  1.38873015],
       [ 0.        ,  0.9258201 ,  1.8516402 ]])